### ISSUE TITLE
Had to force quit the app

### ISSUE THREAD

**Issue by jglovier** [avatsaev/touchbar_nyancat#10]
I closed the window and the music was still playing, and the app was still running (in the menu bar), but there was no way to fully quit the app. I had to force quit it.

Not sure if that's a bug, or that's just how it works right now, but it'd be rad for the whole app to quit when you close the animation window.

Super cool app BTW! The novelty of this will not soon wear off. 😄

**Comment by avatsaev** [comment]
Right click on the dock icon allows you to close the app properly

**Comment by jglovier** [comment]
FYI I've tried this a number of times and it is consistent (having to force quit).

**Comment by avatsaev** [comment]
do you mean like force quit via the task manager (cmd+alt+esc) ?

**Comment by jglovier** [comment]
Yeah, I was just trying to do cmd+q, but when I tried what you suggested that works. Although, I have like a billion things open in the dock so I never use it (see screenshot below lol), so having an alternate close method would be rad.
![image](https://cloud.githubusercontent.com/assets/1319791/20651422/459c24fe-b4b3-11e6-90f5-ee6e4bc549e5.png)
