### ISSUE TITLE
Animation doesn't display fully on touch bar

### ISSUE THREAD

**Issue by alsoknownasfoo** [avatsaev/touchbar_nyancat#19]
Gif Y position seems to be off so animation is partially cut off.

Error:
touchbar_nyancat[10569:539899] Warning: Expected min height of view: (<NSView: 0x7fcaa8c356d0>) to be less than or equal to 30 but got a height of 38.000000. This error will be logged once per view in violation.

It may be worth noting that I have SetResX to set my screen to the native resolution of 2880x1800.

**Comment by jpwalsh1** [comment]
Look in the code and update the 30s to 38 and it will build again.

**Comment by jmb** [comment]
Actually I think the fix is to change the constraints in the storyboard for the touchbar from 38 to 30. I've submitted a PR #25 for this - I hope that's ok.
