### ISSUE TITLE
Video or it didn't happen!

### ISSUE THREAD

**Issue by frnhr** [avatsaev/touchbar_nyancat#2]
I'm contemplating buying the new Mac, and this is one of the most impactful factors in my decision: can Nyancat run across the new touchbar or not. If the quality of the animation is sufficient, I will have no choice other then to buy the Mac. And if it is accompanied by the soundtrack we all know an love, we will never be able to turn the device off, ever!
As I'm sure that almost every other potential buyer of the new MacBook faces the very same dilemma, I respectfully request a video be added to README.md so that all of us could make an informed decision.
Thank you

**Comment by avatsaev** [comment]
Video added to README.md, I'm closing the issue.

**Comment by 3ji7ja0jb9c** [comment]
http://www.youtube.com/watch?v=qLEwZxxTDPA

**Comment by 3ji7ja0jb9c** [comment]
[Video is missing.  This issue is of utmost importance.](/avatsaev/touchbar_nyancat/commit/582ee53e18b1fe6ecdb565a044b0d106d93b4a89?#diff-04c6e90faac2675aa89e2176d2eec7d8)
