### ISSUE TITLE
Running the bar

### ISSUE THREAD

**Issue by leozito22** [avatsaev/touchbar_nyancat#20]
Someone can do a tutorial for newbies like me? What is the step below downloading the file? I do know how to run this Bar. Thanks a lot and sorry for all.

**Comment by avatsaev** [comment]
step 1: download

step 2: run

step 3: there is no step 3

**Comment by leozito22** [comment]
It seems simple, but when I try to run nothing happens, I need some complement?

**Comment by avatsaev** [comment]
try downloading again, i reuploaded the app
