### ISSUE TITLE
Mind if I fork and add to the project?

### ISSUE THREAD

**Issue by groeneveld** [avatsaev/touchbar_nyancat#21]
I noticed you don't have a license but do have 'all rights reserved' in the source files.

I'd keep your name on the source files and readme along with with mine.

**Comment by avatsaev** [comment]
You can fork if you want, but nyancat is a trademark, that's why i didn't add a licence.

A lawyer contacted me, so i had to redo the code, so if you fork, i'm not liable for anything lol.
