### ISSUE TITLE
App crashes in Mojave

### ISSUE THREAD

**Issue by ibzib** [avatsaev/touchbar_nyancat#31]
When I try to run the app in Mojave Version 10.14.2, the app crashes immediately upon opening. The crash report contains the following information:

`Crashing on exception: The window has been marked as needing another Layout Window pass, but it has already had more Layout Window passes than there are views in the window.`

**Comment by jevinskie** [comment]
`defaults write com.vatsaev.touchbar-nyancat NSWindowAssertWhenDisplayCycleLimitReached -bool false`

Now I can finally sleep again at night. I have no idea why AppKit is upset all of the sudden but I don't care as long as I have my precious Nyan Cat in my Touch Bar.

**Comment by ibzib** [comment]
Excellent, now I can nyan to my heart's content.
