### ISSUE TITLE
Not Working On macOS Mojave v10.14.6

### ISSUE THREAD

**Issue by hanothemano** [avatsaev/touchbar_nyancat#35]
touchbar_nyancat is not working on mojave for 15inch pro macbook :(

**Comment by jasminkimm** [comment]
Same

**Comment by utaysi** [comment]
Same on Catalina, outdated still.

**Comment by rocknamx8** [comment]
It can't work in Catalina and mbp13 2020 and mbp16

**Comment by r12habh** [comment]
sudo spctl --master-disable

use this to disable GateKeeper in MacOS

Then goto security and preferences in System Preference and then Choose anywhere in Allow apps to download from

**Comment by kreeble** [comment]
> It can't work in Catalina and mbp13 2020 and mbp16

How come? Need some nyan

**Comment by r12habh** [comment]
> > It can't work in Catalina and mbp13 2020 and mbp16
> 
> How come? Need some nyan

Because MacOS has GateKeeper which doesn't allow you to side load non-trusted apps.

**Comment by avatsaev** [comment]
Bypass the gatekeeper by right clicking the app and then clicking `Open`

**Comment by kreeble** [comment]
Right clicking and opening app didn't work for me on 10.15.7
