### ISSUE TITLE
not working in the v10.15.4

### ISSUE THREAD

**Issue by hwhwhwei** [avatsaev/touchbar_nyancat#36]
When I open the app, it could play music but doesn't show on Touch Bar

**Comment by avatsaev** [comment]
Works fine, the window must be in focus so the touchbar can show nyancat.

**Comment by hwhwhwei** [comment]
But I have already focused, it still doesn't work😭

**Comment by hwhwhwei** [comment]
> Works fine, the window must be in focus so the touchbar can show nyancat.
But I have already focused, it still doesn't work😭
